starfield_pattern_names_6_0_2014  = ['equator_000.mat',
                            'equator_030.mat',
                            'equator_060.mat',
                            'equator_090.mat',
                            'equator_120.mat',
                            'equator_150.mat',
                            'equator_180.mat',
                            'equator_210.mat',
                            'equator_240.mat',
                            'equator_270.mat',
                            'equator_300.mat',
                            'equator_330.mat',
                            'coromeridian_030.mat',
                            'coromeridian_060.mat',
                            'coromeridian_090.mat',
                            'coromeridian_120.mat',
                            'coromeridian_150.mat',
                            'coromeridian_210.mat',
                            'coromeridian_240.mat',
                            'coromeridian_270.mat',
                            'coromeridian_300.mat',
                            'coromeridian_330.mat',
                            'sagimeridian_030.mat',
                            'sagimeridian_060.mat',
                            'sagimeridian_120.mat',
                            'sagimeridian_150.mat',
                            'sagimeridian_210.mat',
                            'sagimeridian_240.mat',
                            'sagimeridian_300.mat',
                            'sagimeridian_330.mat']

starfield_pattern_names_6_29_2014  = ['translate_forward.mat',
                            'translate_backward.mat',
                            'translate_up.mat',
                            'translate_down.mat',
                            'spin_equator_000.mat',
                            'spin_equator_030.mat',
                            'spin_equator_060.mat',
                            'spin_equator_090.mat',
                            'spin_equator_120.mat',
                            'spin_equator_150.mat',
                            'spin_equator_180.mat',
                            'spin_equator_210.mat',
                            'spin_equator_240.mat',
                            'spin_equator_270.mat',
                            'spin_equator_300.mat',
                            'spin_equator_330.mat']

l = [[x,x,x] for x in starfield_pattern_names_6_29_2014]
starfield_pattern_names_6_29_2014 = [item for sublist in l for item in sublist]

test_pattern_names  = ['static_test_90.mat',
                       'static_test_270.mat',
                       'stripe_test_90.mat',
                       'stripe_test_270.mat',
                       'opti_test_90.mat',
                       'opti_test_270.mat']
